In [1]:
!nvidia-smi

Thu Feb 22 09:49:22 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.154.05             Driver Version: 535.154.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 4090 D      Off | 00000000:01:00.0 Off |                  Off |
| 30%   29C    P8              43W / 425W |      1MiB / 24564MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [2]:
import torch
torch.cuda.is_available()

True

In [3]:
# After training, you can use vae.predict(x_test) to reconstruct inputs
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches

In [4]:
import nltk
from nltk.tokenize import word_tokenize

# Download the necessary NLTK models (if you haven't already)
nltk.download('punkt')

# The sentences
sentences = [
    "Dr. Smith's email, j.smith@university.edu, includes a period and an \"at\" symbol (@), and his office number is 456-7890.",
    "\"The quick brown fox jumps over the lazy dog,\" exclaimed Jane, marveling at how the sentence includes every letter of the alphabet!",
    "In her recipe book, Emily noted: \"Mix 2 cups of flour, 1.5 cups of sugar, and 3/4 teaspoon of salt; then, add 100g of butter.\"",
    "The company's revenue increased by 15% in Q4 2023; however, the CEO warned, \"Expect a -5% adjustment due to market fluctuations.\"",
    "\"Did you know,\" asked Tom, \"that '#' is called a 'hash', '&' is an 'ampersand', and '~' is a 'tilde'?\"",
    "The mathematician wrote, \"When x > 3 and y < 5, the function f(x, y) = 3x² + 2y yields values between 27 and 49.\"",
    "In his novel, the author described a peculiar device: \"It's called the 'Chrono-Synclastic Infundibulum'—a portal to parallel universes!\"",
    "The file path C:\\Users\\Lachlan\\Documents\\Project_XYZ\\Report_v3.1.txt includes various punctuation marks used in computer directories.",
    "On the sign-up form, fields such as name, email (e.g., john.doe@example.com), and password (e.g., Pa$$w0rd!) were mandatory.",
    "The biologist noted, \"Species 'Homo sapiens' (human) is distinct in its use of complex symbols, such as alphabets (A-Z) and numbers (0-9).\""
]

# Tokenizing each sentence
tokenized_sentences = [word_tokenize(sentence) for sentence in sentences]

# Printing the tokenized sentences
for i, tokens in enumerate(tokenized_sentences):
    print(f"Sentence {i+1} tokens:")
    print(tokens)
    print("\n")
import nltk
from nltk.tokenize import word_tokenize

# Download the necessary NLTK models (if you haven't already)
nltk.download('punkt')

# The sentences
sentences = [
    "Dr. Smith's email, j.smith@university.edu, includes a period and an \"at\" symbol (@), and his office number is 456-7890.",
    "\"The quick brown fox jumps over the lazy dog,\" exclaimed Jane, marveling at how the sentence includes every letter of the alphabet!",
    "In her recipe book, Emily noted: \"Mix 2 cups of flour, 1.5 cups of sugar, and 3/4 teaspoon of salt; then, add 100g of butter.\"",
    "The company's revenue increased by 15% in Q4 2023; however, the CEO warned, \"Expect a -5% adjustment due to market fluctuations.\"",
    "\"Did you know,\" asked Tom, \"that '#' is called a 'hash', '&' is an 'ampersand', and '~' is a 'tilde'?\"",
    "The mathematician wrote, \"When x > 3 and y < 5, the function f(x, y) = 3x² + 2y yields values between 27 and 49.\"",
    "In his novel, the author described a peculiar device: \"It's called the 'Chrono-Synclastic Infundibulum'—a portal to parallel universes!\"",
    "The file path C:\\Users\\Lachlan\\Documents\\Project_XYZ\\Report_v3.1.txt includes various punctuation marks used in computer directories.",
    "On the sign-up form, fields such as name, email (e.g., john.doe@example.com), and password (e.g., Pa$$w0rd!) were mandatory.",
    "The biologist noted, \"Species 'Homo sapiens' (human) is distinct in its use of complex symbols, such as alphabets (A-Z) and numbers (0-9).\""
]

# Tokenizing each sentence
tokenized_sentences = [word_tokenize(sentence) for sentence in sentences]

# Printing the tokenized sentences
for i, tokens in enumerate(tokenized_sentences):
    print(f"Sentence {i+1} tokens:")
    print(tokens)
    print("\n")


Sentence 1 tokens:
['Dr.', 'Smith', "'s", 'email', ',', 'j.smith', '@', 'university.edu', ',', 'includes', 'a', 'period', 'and', 'an', '``', 'at', "''", 'symbol', '(', '@', ')', ',', 'and', 'his', 'office', 'number', 'is', '456-7890', '.']


Sentence 2 tokens:
['``', 'The', 'quick', 'brown', 'fox', 'jumps', 'over', 'the', 'lazy', 'dog', ',', "''", 'exclaimed', 'Jane', ',', 'marveling', 'at', 'how', 'the', 'sentence', 'includes', 'every', 'letter', 'of', 'the', 'alphabet', '!']


Sentence 3 tokens:
['In', 'her', 'recipe', 'book', ',', 'Emily', 'noted', ':', '``', 'Mix', '2', 'cups', 'of', 'flour', ',', '1.5', 'cups', 'of', 'sugar', ',', 'and', '3/4', 'teaspoon', 'of', 'salt', ';', 'then', ',', 'add', '100g', 'of', 'butter', '.', "''"]


Sentence 4 tokens:
['The', 'company', "'s", 'revenue', 'increased', 'by', '15', '%', 'in', 'Q4', '2023', ';', 'however', ',', 'the', 'CEO', 'warned', ',', '``', 'Expect', 'a', '-5', '%', 'adjustment', 'due', 'to', 'market', 'fluctuations', '.', "''"]


S

[nltk_data] Downloading package punkt to /home/lachlan/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt to /home/lachlan/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [5]:
import numpy as np

# ASCII character set
characters = [chr(i) for i in range(128)]

# Create a mapping from characters to their index in ASCII
char_to_index = {char: idx for idx, char in enumerate(characters)}

# Create a mapping from index in ASCII to characters
index_to_char = {idx: char for char, idx in char_to_index.items()}

def one_hot_encode(char):
    """One hot encode a single character."""
    vector = np.zeros(len(characters))
    vector[char_to_index[char]] = 1
    return vector

def encode_word(word):
    """Encode a word into a 128x128 matrix using Numpy optimizations."""
    # Create an empty matrix filled with the one hot encoding of NUL character
    matrix = np.tile(one_hot_encode('\x00'), (128, 1))

    # Calculate the indices where each character's one-hot encoding will be placed
    step = max(1, int(128 / len(word)))
    indices = np.arange(len(word)) * step

    # Create one-hot encodings for all characters in the word at once
    char_vectors = np.array([one_hot_encode(char) for char in word])

    # Place the character one-hot encodings into the matrix
    matrix[indices] = char_vectors

    return matrix


def decode_matrix(matrix):
    """Decode a 128x128 matrix into a word, ignoring NUL characters, using Numpy optimizations."""
    # Find the index with the maximum value (one-hot encoded character) in each row
    char_indices = np.argmax(matrix, axis=1)

    # Convert indices to characters
    chars = np.array([index_to_char[idx] for idx in char_indices])

    # Filter out NUL characters and join the rest into a word
    word = ''.join(chars[chars != '\x00'])

    return word

# Test the functions
word = 'a'
encoded_matrix = encode_word(word)
decoded_word = decode_matrix(encoded_matrix)

print(f'Encoded Matrix for "{word}":\n{encoded_matrix}')
print(f'Decoded Word: {decoded_word}')
sns.heatmap(encoded_matrix)

Encoded Matrix for "a":
[[0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]]
Decoded Word: a


NameError: name 'sns' is not defined

In [6]:
import numpy as np
import nltk
from nltk.tokenize import word_tokenize

# Function Definitions (one_hot_encode, encode_word, decode_matrix) remain the same as before
def one_hot_encode(char):
    """One hot encode a single character. Ignore characters not in the ASCII range."""
    vector = np.zeros(len(characters))
    if char in char_to_index:  # Check if the character is in the ASCII range
        vector[char_to_index[char]] = 1
    return vector

# The rest of your code remains the same


def encode_word(word):
    """Encode a word into a 128x128 matrix using Numpy optimizations."""
    # Create an empty matrix filled with the one hot encoding of NUL character
    matrix = np.tile(one_hot_encode('\x00'), (128, 1))

    # Calculate the indices where each character's one-hot encoding will be placed
    step = max(1, int(128 / len(word)))
    indices = np.arange(len(word)) * step

    # Create one-hot encodings for all characters in the word at once
    char_vectors = np.array([one_hot_encode(char) for char in word])

    # Place the character one-hot encodings into the matrix
    matrix[indices] = char_vectors

    return matrix


def decode_matrix(matrix):
    """Decode a 128x128 matrix into a word, ignoring NUL characters, using Numpy optimizations."""
    # Find the index with the maximum value (one-hot encoded character) in each row
    char_indices = np.argmax(matrix, axis=1)

    # Convert indices to characters
    chars = np.array([index_to_char[idx] for idx in char_indices])

    # Filter out NUL characters and join the rest into a word
    word = ''.join(chars[chars != '\x00'])

    return word

# Tokenize Sentences
nltk.download('punkt')
sentences = [
    "Dr. Smith's email, j.smith@university.edu, includes a period and an \"at\" symbol (@), and his office number is 456-7890.",
    "\"The quick brown fox jumps over the lazy dog,\" exclaimed Jane, marveling at how the sentence includes every letter of the alphabet!",
    "In her recipe book, Emily noted: \"Mix 2 cups of flour, 1.5 cups of sugar, and 3/4 teaspoon of salt; then, add 100g of butter.\"",
    "The company's revenue increased by 15% in Q4 2023; however, the CEO warned, \"Expect a -5% adjustment due to market fluctuations.\"",
    "\"Did you know,\" asked Tom, \"that '#' is called a 'hash', '&' is an 'ampersand', and '~' is a 'tilde'?\"",
    "The mathematician wrote, \"When x > 3 and y < 5, the function f(x, y) = 3x² + 2y yields values between 27 and 49.\"",
    "In his novel, the author described a peculiar device: \"It's called the 'Chrono-Synclastic Infundibulum'—a portal to parallel universes!\"",
    "The file path C:\\Users\\Lachlan\\Documents\\Project_XYZ\\Report_v3.1.txt includes various punctuation marks used in computer directories.",
    "On the sign-up form, fields such as name, email (e.g., john.doe@example.com), and password (e.g., Pa$$w0rd!) were mandatory.",
    "The biologist noted, \"Species 'Homo sapiens' (human) is distinct in its use of complex symbols, such as alphabets (A-Z) and numbers (0-9).\""
]
tokenized_sentences = [word_tokenize(sentence) for sentence in sentences]

# Create a set of unique tokens
unique_tokens = set(token for sentence in tokenized_sentences for token in sentence)

# Encode each unique token into a 128x128 matrix
token_matrices = {token: encode_word(token) for token in unique_tokens}

# Optional: Convert the dictionary of matrices to a list or array if needed
matrix_dataset = list(token_matrices.values())

# Print some of the encoded matrices
for token, matrix in list(token_matrices.items())[:5]:  # print first 5 for brevity
    print(f'Encoded Matrix for "{token}":\n{matrix}\n')

# Decoding back (optional)
for token, matrix in list(token_matrices.items())[:5]:  # print first 5 for brevity
    decoded_word = decode_matrix(matrix)
    print(f'Decoded Word for matrix of "{token}": {decoded_word}')


Encoded Matrix for "3/4":
[[0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]]

Encoded Matrix for "symbols":
[[0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]]

Encoded Matrix for "``":
[[0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]]

Encoded Matrix for "letter":
[[0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]]

Encoded Matrix for "49":
[[0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]]

Decoded Word for matrix of "3/4": 3/4
Decoded Word for matrix of "symbols": symb

[nltk_data] Downloading package punkt to /home/lachlan/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [27]:
import numpy as np
import tensorflow as tf
import tensorflow_probability as tfp
from tensorflow.keras import layers, Model, losses, optimizers

tfd = tfp.distributions


class CustomVAE(Model):
    def __init__(self, **kwargs):
        super(CustomVAE, self).__init__(**kwargs)
        self.encoder = self.build_encoder()
        self.intermediate = self.build_intermediate()
        self.decoder = self.build_decoder()

        # Temperature for SoftFloor bijector
        self.temperature = 0.1
        self.softfloor = tfp.bijectors.Softfloor(temperature=self.temperature)

    def build_encoder(self):
        inputs = tf.keras.Input(shape=(128, 128, 1))
        x = layers.Conv2D(32, 3, activation='relu', padding='same')(inputs)
        x = layers.MaxPooling2D()(x)
        x = layers.Conv2D(64, 3, activation='relu', padding='same')(x)
        x = layers.MaxPooling2D()(x)
        x = layers.Flatten()(x)
        x = layers.Dense(128, activation='relu')(x)
        z_mean = layers.Dense(3, name='z_mean')(x)
        z_log_var = layers.Dense(3, name='z_log_var')(x)
        encoder = tf.keras.Model(inputs, [z_mean, z_log_var], name='encoder')
        return encoder

    def build_intermediate(self):
        # This method may not be necessary if it does not contribute to the model.
        # Adjustments made to ensure it aligns with the intended model structure.
        # For simplicity, the intermediate step has been integrated into the encoder.
        pass

    def build_decoder(self):
        latent_inputs = tf.keras.Input(shape=(3,))
        x = layers.Dense(64 * 32 * 32, activation='relu')(latent_inputs)
        x = layers.Reshape((32, 32, 64))(x)
        x = layers.Conv2DTranspose(64, 3, activation='relu', padding='same')(x)
        x = layers.UpSampling2D()(x)
        x = layers.Conv2DTranspose(32, 3, activation='relu', padding='same')(x)
        x = layers.UpSampling2D()(x)
        outputs = layers.Conv2DTranspose(1, 3, activation='sigmoid', padding='same')(x)
        decoder = tf.keras.Model(latent_inputs, outputs, name='decoder')
        return decoder

    def sample(self, z_mean, z_log_var):
        batch = tf.shape(z_mean)[0]
        dim = tf.shape(z_mean)[1]
        epsilon = tf.keras.backend.random_normal(shape=(batch, dim))
        return z_mean + tf.exp(0.5 * z_log_var) * epsilon

    def call(self, inputs, training=False):
        z_mean, z_log_var = self.encoder(inputs)
        z = self.sample(z_mean, z_log_var)
        reconstructed = self.decoder(z)
        return reconstructed

    def train_step(self, data):
        with tf.GradientTape() as tape:
            z_mean, z_log_var = self.encoder(data)
            z = self.sample(z_mean, z_log_var)
            reconstruction = self.decoder(z)
            reconstruction_loss = tf.reduce_mean(
                tf.reduce_sum(
                    losses.binary_crossentropy(data, reconstruction), axis=(1, 2)
                )
            )
            kl_loss = -0.5 * tf.reduce_mean(
                tf.reduce_sum(1 + z_log_var - tf.square(z_mean) - tf.exp(z_log_var), axis=1)
            )
            total_loss = reconstruction_loss + kl_loss
        grads = tape.gradient(total_loss, self.trainable_variables)
        self.optimizer.apply_gradients(zip(grads, self.trainable_variables))
        return {"loss": total_loss, "reconstruction_loss": reconstruction_loss, "kl_loss": kl_loss}


# Instantiate and compile the VAE
vae = CustomVAE()
vae.compile(optimizer=optimizers.Adam())

# Assuming x_train is your dataset of 128x128 matrices
# Replace `matrix_dataset` with your actual dataset variable
x_train = np.array(matrix_dataset).astype('float32') # / 255.0  # Normalize to [0, 1]
x_train = np.expand_dims(x_train, axis=-1)  # Add channel dimension

# Placeholder for dataset loading, uncomment and modify the above lines accordingly
# Train the VAE
vae.fit(x_train, epochs=1000, batch_size=64)


Epoch 1/1000
3/3 [==============================] - 2s 344ms/step - loss: 11209.2651 - reconstruction_loss: 11209.1963 - kl_loss: 0.0689
Epoch 2/1000
3/3 [==============================] - 1s 332ms/step - loss: 10397.9602 - reconstruction_loss: 10397.4570 - kl_loss: 0.5032
Epoch 3/1000
3/3 [==============================] - 1s 305ms/step - loss: 7155.8882 - reconstruction_loss: 7150.5618 - kl_loss: 5.3263
Epoch 4/1000
3/3 [==============================] - 1s 335ms/step - loss: 1531.9581 - reconstruction_loss: 1486.9508 - kl_loss: 45.0072
Epoch 5/1000
3/3 [==============================] - 1s 350ms/step - loss: 850.4412 - reconstruction_loss: 675.3561 - kl_loss: 175.0850
Epoch 6/1000
3/3 [==============================] - 1s 371ms/step - loss: 1093.0424 - reconstruction_loss: 843.1794 - kl_loss: 249.8630
Epoch 7/1000
3/3 [==============================] - 1s 335ms/step - loss: 873.1049 - reconstruction_loss: 643.1492 - kl_loss: 229.9557
Epoch 8/1000
3/3 [==============================]

KeyboardInterrupt: 

In [28]:

x_train.shape

(170, 128, 128, 1)

In [29]:
import seaborn as sns
from pprint import pprint

def visualize_components(model, input_matrix, input_word=None):
    reconstructed, z_3_vector, z_mu, sigma, z_scalar, v = model(input_matrix, return_components=True)

    fig, axes = plt.subplots(1, 7, figsize=(21, 3))

    # Input word (matrix)
    axes[0].imshow(input_matrix[0, :, :, 0], cmap='gray')
    axes[0].set_title(f"Input Word\n{input_word if input_word else ''}")

    # 3-vector v
    axes[2].bar(['Dim1', 'Dim2', 'Dim3'], v[0, :])
    axes[2].set_title("3-Vector v\n" + '\n'.join([f"{val:.4f}" for val in v[0, :]]))

    # 3-vector z_3_vector
    axes[1].bar(['Dim1', 'Dim2', 'Dim3'], z_3_vector[0, :])
    axes[1].set_title("3-Vector z\n" + '\n'.join([f"{val:.4f}" for val in z_3_vector[0, :]]))

    # Scalar mu
    axes[3].bar(['Scalar Mu'], z_mu[0, 0])
    axes[3].set_title(f"Scalar Mu\n{z_mu[0, 0]:.4f}")

    # Scalar sigma
    axes[4].bar(['Scalar Sigma'], sigma[0, 0])
    axes[4].set_title(f"Scalar Sigma\n{sigma[0, 0]:.4f}")

    # Sampled z
    axes[5].bar(['Sampled Z'], z_scalar[0, 0])
    axes[5].set_title(f"Sampled Z\n{z_scalar[0, 0]:.4f}")

    # Reconstructed word (matrix)
    axes[6].imshow(reconstructed[0, :, :, 0], cmap='gray')
    axes[6].set_title(f"Reconstructed\n{decode_matrix(reconstructed[0, :, :, 0])}")
    
    pprint(reconstructed[0, :, :, 0])

    for ax in axes:
        ax.axis('off')

    plt.tight_layout()
    plt.show()


def decode_matrix(matrix):
    """Decode a 128x128 matrix into a word, ignoring NUL characters."""
    word = ''
    for row in matrix:
        if row.ndim > 1:  # If row is 2D (for batched input), we take the first axis
            row = row[0]
        char_index = np.argmax(row)
        char = index_to_char[char_index]
        if char == '\x00':  # Skip if NUL character is found
            continue
        word += char
    return word

# Choose an example
example_index = 23  # Change this index to see different examples
example_input = x_train[example_index:example_index+1]  # Get a single example
print(example_input.shape)
input_word = decode_matrix(example_input[0, :,:, 0])  # Replace with the actual word or leave it as None

# Visualize the components
visualize_components(vae, example_input, input_word=input_word)


(1, 128, 128, 1)


TypeError: CustomVAE.call() got an unexpected keyword argument 'return_components'